// Date: 5/27/2015 6:57:54 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package ninja.techiecrow.renderers;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class XenBeastModel extends ModelBase
{
	// fields
	ModelRenderer head;
	ModelRenderer UpperBody;
	ModelRenderer body;
	ModelRenderer rightarm;
	ModelRenderer leftarm;
	ModelRenderer rightleg;
	ModelRenderer leftleg;
	ModelRenderer LUpperLeg;
	ModelRenderer RUpperLeg;
	ModelRenderer Rshoulder;
	ModelRenderer Lshoulder;

	public XenBeastModel()
	{
		textureWidth = 128;
		textureHeight = 64;

		head = new ModelRenderer(this, 0, 0);
		head.addBox(-4F, -8F, -4F, 8, 8, 8);
		head.setRotationPoint(0F, -15F, 0F);
		head.setTextureSize(128, 64);
		head.mirror = true;
		setRotation(head, 0F, 0F, 0F);
		UpperBody = new ModelRenderer(this, 0, 46);
		UpperBody.addBox(0F, 0F, 0F, 14, 10, 8);
		UpperBody.setRotationPoint(-7F, -15F, -4F);
		UpperBody.setTextureSize(128, 64);
		UpperBody.mirror = true;
		setRotation(UpperBody, 0F, 0F, 0F);
		body = new ModelRenderer(this, 90, 26);
		body.addBox(-4F, 0F, -2F, 10, 19, 4);
		body.setRotationPoint(-1F, -13F, 0F);
		body.setTextureSize(128, 64);
		body.mirror = true;
		setRotation(body, 0F, 0F, 0F);
		rightarm = new ModelRenderer(this, 94, 1);
		rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
		rightarm.setRotationPoint(-8F, -9F, 0F);
		rightarm.setTextureSize(128, 64);
		rightarm.mirror = true;
		setRotation(rightarm, 0F, 0F, 0F);
		leftarm = new ModelRenderer(this, 111, 1);
		leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
		leftarm.setRotationPoint(8F, -9F, 0F);
		leftarm.setTextureSize(128, 64);
		leftarm.mirror = true;
		setRotation(leftarm, 0F, 0F, 0F);
		rightleg = new ModelRenderer(this, 40, 16);
		rightleg.addBox(-2F, 0F, -2F, 4, 10, 4);
		rightleg.setRotationPoint(-2F, 14F, 0F);
		rightleg.setTextureSize(128, 64);
		rightleg.mirror = true;
		setRotation(rightleg, 0F, 0F, 0F);
		leftleg = new ModelRenderer(this, 59, 16);
		leftleg.addBox(-2F, 0F, -2F, 4, 10, 4);
		leftleg.setRotationPoint(2F, 14F, 0F);
		leftleg.setTextureSize(128, 64);
		leftleg.mirror = true;
		setRotation(leftleg, 0F, 0F, 0F);
		LUpperLeg = new ModelRenderer(this, 59, 31);
		LUpperLeg.addBox(0F, 0F, 0F, 4, 8, 4);
		LUpperLeg.setRotationPoint(0F, 6F, -2F);
		LUpperLeg.setTextureSize(128, 64);
		LUpperLeg.mirror = true;
		setRotation(LUpperLeg, 0F, 0F, 0F);
		RUpperLeg = new ModelRenderer(this, 40, 31);
		RUpperLeg.addBox(0F, 0F, 0F, 4, 8, 4);
		RUpperLeg.setRotationPoint(-4F, 6F, -2F);
		RUpperLeg.setTextureSize(128, 64);
		RUpperLeg.mirror = true;
		setRotation(RUpperLeg, 0F, 0F, 0F);
		Rshoulder = new ModelRenderer(this, 57, 3);
		Rshoulder.addBox(0F, 0F, 0F, 5, 4, 6);
		Rshoulder.setRotationPoint(-12F, -15F, -3F);
		Rshoulder.setTextureSize(128, 64);
		Rshoulder.mirror = true;
		setRotation(Rshoulder, 0F, 0F, 0F);
		Lshoulder = new ModelRenderer(this, 34, 3);
		Lshoulder.addBox(0F, 0F, 0F, 5, 4, 6);
		Lshoulder.setRotationPoint(7F, -15F, -3F);
		Lshoulder.setTextureSize(128, 64);
		Lshoulder.mirror = true;
		setRotation(Lshoulder, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5);
		head.render(f5);
		UpperBody.render(f5);
		body.render(f5);
		rightarm.render(f5);
		leftarm.render(f5);
		rightleg.render(f5);
		leftleg.render(f5);
		LUpperLeg.render(f5);
		RUpperLeg.render(f5);
		Rshoulder.render(f5);
		Lshoulder.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
	}

}
